repos:

# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: mixed-line-ending
  - id: requirements-txt-fixer

# Ruff (replaces Black, Flake8, isort, and more)
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.0
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    exclude: ^tests/
    additional_dependencies:
      - types-all  # Add if you want comprehensive type stubs

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py312-plus]
