site_name: pydavinci Docs

repo_url: https://github.com/pedrolabonia/pydavinci

nav:
  - Home: index.md
  # - Quickstart: quickstart.md
  - Examples:
    - "Create Premiere Proxies": "examples/premiereproxies.md"
  - API Reference:
    - "Resolve": resolve.md
    - "ProjectManager": projectmanager.md
    - "Project": project.md
    - "MediaStorage": mediastorage.md
    - "MediaPool": mediapool.md
    - "MediaPool Item": mediapoolitem.md
    - "Folder": folder.md
    - "Timeline": timeline.md
    - "TimelineItem": timelineitem.md

theme:
  name: "material"
  palette:
    primary: purple
    scheme: slate
  features:
    - content.code.annotate



plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            members_order: source
            heading_level: 2
            show_root_toc_entry: false
            show_root_heading: false
            show_if_no_docstring: false
            show_object_full_path: true
            show_root_members_full_path: false
            group_by_category: true
            show_category_heading: true
            show_source: false
            merge_init_into_class: true
            separate_signature: false
            docstring_section_style: table
            show_signature_annotations: false
      custom_templates: docs/templates

      watch:
        - pydavinci
        - docs/css
        - docs/templates/
  - autorefs
  

extra_css:
- css/style.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
